### ISSUE TITLE
Error: newman-reporter-html@1.0.1 requires a peer of newman@4 but none is installed. You must install peer dependencies yourself.

### ISSUE THREAD

**Issue by KonstantinxVx** [postmanlabs/newman-reporter-html#10]
Hello,

I'm trying to install `newman-reporter-html` and I'm facing this error:

```
$ npm install -g newman-reporter-html
npm WARN newman-reporter-html@1.0.1 requires a peer of newman@4 but none is installed. You must install peer dependencies yourself.

+ newman-reporter-html@1.0.1
updated 1 package in 1.704s
```
Version of my newman:
```
$ newman -v
4.0.1
```

Please help me to figure out how to avoid/fix it.

Thanks in advance!

**Comment by codenirvana** [comment]
@KonstantinxVx Thanks for reporting.

This is just a warning, you can ignore that. We are aware of this, known issue in [npm](https://github.com/npm/npm/issues/9857).

Are you facing any other issue while using the reporter?

**Comment by KonstantinxVx** [comment]
@codenirvana alright then, thanks for your reply.
Repoter seems to be working, just checked.

**Comment by JoeDream** [comment]
I had the same problem with it，I don't know if you 've resolved this warning，If it works out, I hope you can share it，Thanks in advance ! this is my software environment.

C:\Windows\system32>npm install -g newman-reporter-html
npm WARN newman-reporter-html@1.0.3 requires a peer of newman@4 but none is installed. You must install peer dependencies yourself.

+ newman-reporter-html@1.0.3
updated 1 package in 2.893s

C:\Windows\system32>newman -v
4.5.1
C:\Windows\system32>npm -v
6.9.0
C:\Windows\system32>node -v
v10.16.0

I used other methods to generate reports.
eg：C:\Windows\system32>newman run D:\postmanword\agent.postman_collection.json  -e d:\postmanword\agent.postman_environment.json  --reporters html --reporter-html-export D:/postmanword/agent01.html

**Comment by jmorrisfmc** [comment]
> I had the same problem with it，I don't know if you 've resolved this warning，If it works out, I hope you can share it，Thanks in advance ! this is my software environment.
> 
> C:\Windows\system32>npm install -g newman-reporter-html
> npm WARN newman-reporter-html@1.0.3 requires a peer of newman@4 but none is installed. You must install peer dependencies yourself.
> 
> * newman-reporter-html@1.0.3
>   updated 1 package in 2.893s
> 
> C:\Windows\system32>newman -v
> 4.5.1
> C:\Windows\system32>npm -v
> 6.9.0
> C:\Windows\system32>node -v
> v10.16.0
> 
> I used other methods to generate reports.
> eg：C:\Windows\system32>newman run D:\postmanword\agent.postman_collection.json -e d:\postmanword\agent.postman_environment.json --reporters html --reporter-html-export D:/postmanword/agent01.html

Really useful! Thanks!

**Comment by saifk313** [comment]
Hello,

I am a new man to newman html extra reports!

I successfully installed newman-reporter-htmlextra, but when I run the command from cli "newman run collection.json -r htmlextra" is gives me error as "'newman' is not recognized as an internal or external command, operable program or batch file."

What could be the possible reason for this error? Do I need to set PATH variables? Thanks in advance.

Below is what I have done

D:\DGIT>npm install -g newman
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
C:\Users\saif.k.HQ0\AppData\Roaming\npm\newman -> C:\Users\saif.k.HQ0\AppData\Ro
aming\npm\node_modules\newman\bin\newman.js
+ newman@5.2.1
updated 1 package in 17.112s

D:\DGIT>npm install -g newman-reporter-htmlextra
npm WARN deprecated highlight.js@9.18.5: Support has ended for 9.x series. Upgra
de to @latest
npm WARN deprecated gulp-header@1.8.12: Removed event-stream from gulp-header
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprec
ated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#dep
recated
C:\Users\saif.k.HQ0\AppData\Roaming\npm\newman-reporter-htmlextra -> C:\Users\sa
if.k.HQ0\AppData\Roaming\npm\node_modules\newman-reporter-htmlextra\bin\htmlextr
a.js
npm WARN newman-reporter-htmlextra@1.19.6 requires a peer of newman@>=4 but none
 is installed. You must install peer dependencies yourself.

+ newman-reporter-htmlextra@1.19.6
updated 2 packages in 122.513s

D:\DGIT>newman run D:\DGIT\PHR\PHR.postman_collection.json -r htmlextra
'newman' is not recognized as an internal or external command,
operable program or batch file.

D:\DGIT>node -v
v12.18.4

D:\DGIT>npm -v
6.14.6

D:\DGIT>newman -v
'newman' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Sushmitha-9511** [comment]
> Hello,
> 
> I am a new man to newman html extra reports!
> 
> I successfully installed newman-reporter-htmlextra, but when I run the command from cli "newman run collection.json -r htmlextra" is gives me error as "'newman' is not recognized as an internal or external command, operable program or batch file."
> 
> What could be the possible reason for this error? Do I need to set PATH variables? Thanks in advance.
> 
> Below is what I have done
> 
> D:\DGIT>npm install -g newman
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> C:\Users\saif.k.HQ0\AppData\Roaming\npm\newman -> C:\Users\saif.k.HQ0\AppData\Ro
> aming\npm\node_modules\newman\bin\newman.js
> 
> * newman@5.2.1
>   updated 1 package in 17.112s
> 
> D:\DGIT>npm install -g newman-reporter-htmlextra
> npm WARN deprecated highlight.js@9.18.5: Support has ended for 9.x series. Upgra
> de to @latest
> npm WARN deprecated gulp-header@1.8.12: Removed event-stream from gulp-header
> npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprec
> ated
> npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#dep
> recated
> C:\Users\saif.k.HQ0\AppData\Roaming\npm\newman-reporter-htmlextra -> C:\Users\sa
> if.k.HQ0\AppData\Roaming\npm\node_modules\newman-reporter-htmlextra\bin\htmlextr
> a.js
> npm WARN newman-reporter-htmlextra@1.19.6 requires a peer of newman@>=4 but none
> is installed. You must install peer dependencies yourself.
> 
> * newman-reporter-htmlextra@1.19.6
>   updated 2 packages in 122.513s
> 
> D:\DGIT>newman run D:\DGIT\PHR\PHR.postman_collection.json -r htmlextra
> 'newman' is not recognized as an internal or external command,
> operable program or batch file.
> 
> D:\DGIT>node -v
> v12.18.4
> 
> D:\DGIT>npm -v
> 6.14.6
> 
> D:\DGIT>newman -v
> 'newman' is not recognized as an internal or external command,
> operable program or batch file.

**Comment by Sushmitha-9511** [comment]
Hey ypu have to set the npm folder path in the environment variables.
