### ISSUE TITLE
Unable to use version 1.0.3 with newman@4.4.0, "reporter could not be loaded"

### ISSUE THREAD

**Issue by filfreire** [postmanlabs/newman-reporter-html#112]
Hello 👋  @codenirvana  and @kunagpal, seems there's something wrong with using `newman-reporter-html@1.0.3` and `newman@4.4.0`, any ideas?

* Version information:
```
user $node -v
v12.3.1
user $newman -v
4.4.0
user $npm -v
6.9.0
```

* Installing `newman-reporter-html`
```
user $npm install -g newman-reporter-html
npm WARN newman-reporter-html@1.0.3 requires a peer of newman@4 but none is installed. You must install peer dependencies yourself.

+ newman-reporter-html@1.0.3
updated 1 package in 0.536s
```

* Running `newman` after installing reporter:
```
user $newman run c.json --environment e.json --bail --reporters html
newman: "html" reporter could not be loaded.
  run `npm install newman-reporter-html`

```

**Comment by filfreire** [comment]
@codenirvana updating newman to version `4.5.0` seems to have solved the issue.
I'm closing this ticket 😉

**Comment by ibnelhithem** [comment]
Hi filfreire
I have the same issue with newman 4.5.1
do you have a soulution for it ??
Regards

**Comment by gh549427987** [comment]
> Hi filfreire
> I have the same issue with newman 4.5.1
> do you have a soulution for it ??
> Regards

me too,what's your situation now

**Comment by fKrilin** [comment]
Hi, I've got the same issue with newman 4.5.1.
Is there something wrong with the compatibility of these versions ?
- node -v v12.6.0
- npm -v 6.9.0
- newman -v 4.5.1
I tryed to update everything but no result.

Regards.

**Comment by Yosi-bi** [comment]
Hi,
Does anyone have a solution to this?

npm WARN newman-reporter-html@1.0.3 requires a peer of newman@4 but none is installed. You must install peer dependencies yourself

Thx.
