### ISSUE TITLE
Newman script not running with -r tag for both newman-reporter-html or newman-reporter-htmlextra

### ISSUE THREAD

**Issue by satabdisikdar** [postmanlabs/newman-reporter-html#153]
The test scripts don't run with -r tag. On removing this reporter tag, the scripts start running.

**Comment by DannyDainton** [comment]
Hey @satabdisikdar 

What versions of Newman the reporters are you running?

What's the full Newman command that you're running?

**Comment by satabdisikdar** [comment]
Hey @DannyDainton ,

newman run collection.json -e environment.json -r html,cli --reporter-htmlextra-export /home/abc/OMNISCI/admin-console/API_tests/ --insecure

I run this command with the environment variables , location to store the html reports and also --insecure keyword to ignore ssl 
The versions are - 
1. newman : 4.5.6
2. node - 10.14.2

The syntax is -r html,cli to see the tests running on command prompt. If cli is not given then also the tests will run but won't be seen in command prompt. Could you try running it with the above command?

**Comment by DannyDainton** [comment]
Any collection that I run locally is not going to be the same as you're running there :)

I did notice that the command is slightly incorrect:

`newman run collection.json -e environment.json -r html,cli --reporter-htmlextra-export /home/abc/OMNISCI/admin-console/API_tests/ --insecure`

That command has a mix match for the reporter name and the export flag name - If the run didn't error, it would have created the report in the default `/newman` dir, that would have been created in the same directory where the command was run.

You would need to use either:

`newman run collection.json -e environment.json -r html,cli --reporter-html-export /home/abc/OMNISCI/admin-console/API_tests/ --insecure`

Or

`newman run collection.json -e environment.json -r htmlextra,cli --reporter-htmlextra-export /home/abc/OMNISCI/admin-console/API_tests/ --insecure`

**Comment by satabdisikdar** [comment]
yeah @DannyDainton ! I got it. Thanks :)

**Comment by DannyDainton** [comment]
Awesome @satabdisikdar  🏆

Do you want to close the issue if everything is working for you?

**Comment by satabdisikdar** [comment]
Sure. Closing it
