### ISSUE TITLE
Allow option to specify report filename.

### ISSUE THREAD

**Issue by adudiapis** [postmanlabs/newman-reporter-html#16]
This may not be important and irrelevant for many use cases, but I would like to see an option to specify a filename or to include collection name. When I run multiple collections from same location and don't specify folder. Similar to what you already have for json
`newman run mycollection.json --reporters cli,json --reporter-json-export outputfile.json`.

Thanks.

**Comment by codenirvana** [comment]
@adudiapis You can use the `--reporter-html-export` option to do that.

```console
$ newman run collection.json --reporters cli,html --reporter-html-export path/to/report.html
```
Closing this issue for now. Feel free to re-open if it still persists.
