### ISSUE TITLE
could not find "htmlextra" reporter ensure that the reporter is installed int he same directory as newman

### ISSUE THREAD

**Issue by sravanisara** [postmanlabs/newman-reporter-html#213]
Error is show up as below when i execute collection using newman and add reporter to the command

could not find "htmlextra" reporter
ensure that the reporter is installed int he same directory as newman
Please install reporter using npm

npm version :
6.14
node version:
10.21.0
newman version:
5.1.2
htmlextra@1.17.3

executed command as: newman run collection_name.json -r htmlextra
tried with sudo also
intalled the newman in global and
Have the newman and html reporter in same directory

Tried this on ubuntu18.4
Tried uninstalled the nodejs, newman and reinstalled
installed reported with command: sudo npm install -g newman newman-reporter-htmlextra
The error is shown as same

**Comment by DannyDainton** [comment]
Hey @sravanisara,

The is not the `htmlextra` reporter repo, this is the `html` reporter repo.

Can you close this issue and open one up there please.
