### ISSUE TITLE
npm WARN newman-reporter-html@1.0.2 requires a peer of newman@4 but none is installed. You must install peer dependencies yourself.

### ISSUE THREAD

**Issue by ssr240** [postmanlabs/newman-reporter-html#33]
I notice this error and **reports are not generated**. Here are the versions I have

npm -v 
6.4.1

 newman -v
4.1.0

node -v
v10.13.0

PS C:\> npm install -g newman-reporter-html
npm : npm WARN newman-reporter-html@1.0.2 requires a peer of newman@4 but none is installed. You must install peer dependencies yourself.
At line:1 char:1
+ npm install -g newman-reporter-html
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (npm WARN newman...ncies yourself.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
+ newman-reporter-html@1.0.2
updated 1 package in 1.368s

_Originally posted by @ssr240 in https://github.com/postmanlabs/newman-reporter-html/issues/10#issuecomment-434469885_

**Comment by vgadolin** [comment]
I am having the same issue.  Any idea on when this can be resolved?

**Comment by ssr240** [comment]
No idea, I am waiting for someone to help me to resolve it. The only thing I can think of is to uninstall everything and re-install all those packages.

**Comment by vgadolin** [comment]
I was finally able to get this to work.  I had to do the npm install -g newman-reporter-html and also forgot to include -e for my environment.  After that I was able to get this to work in Jenkins.

**Comment by codenirvana** [comment]
@vgadolin Great 👍 

@ssr240 Are you facing any other issue while using the reporter?

**Comment by ssr240** [comment]
@codenirvana ,I did try installing globally and that did not work for me.I am using Powershell to execute the CLI commands.
newman run $newmanCollectionCommand --environment $newmanEnvironmentCommand --reporters cli,html --reporter-html-export \\xxxxxxxxx\c$\PostmanTestsResults --disable-unicode

**Comment by vgadolin** [comment]
Not at this time

**Comment by ssr240** [comment]
@vgadolin ,Can you share the exact command that you have used for generating the report? I already installed HTML report with the command npm install -g newman-reporter-html before posting this issue.

**Comment by vgadolin** [comment]
@ssr240 I am running this in a batch script that Jenkins runs as part of the setup for Postman.  Here is the command that I am using there - note:  I am using the template that is in another thread that another Postman user created.  They also included their index.js file with this template.  When this was broken for me, I had not done the html command to install html and I had removed the -e from the below command.  

Here is the command in the batch script we are using:

CALL newman run --disable-unicode --reporters junit,cli,json,html --reporter-html-template %~dp0template-default-colored.hbs -e %~dp0jenkins.postman_environment.json "%collection_directory%\%%f"

I hope this helps you.

**Comment by ssr240** [comment]
@codenirvana ,Is there a way I can uninstall all the newman packages including html ? Do I need to uninstall NPM ?

**Comment by codenirvana** [comment]
@ssr240 No, don't uninstall NPM.
You can uninstall global packages with `npm uninstall -g <package-name>`.

**Comment by ssr240** [comment]
@codenirvana I still cannot figure out why html reports are not being generated.It works fine with Windows 10 and below are the versions of NPM & Newman 
PS C:\WINDOWS\system32> newman -v
4.1.0

PS C:\WINDOWS\system32> npm -v
5.6.0

PS C:\WINDOWS\system32> node -v
v8.11.1

**but not on Windows Server 2012 and I installed below packages today**

C:\Users>node -v
v10.13.0

C:\Users>npm -v
6.4.1

C:\Users>newman -v
4.2.2

**I notice below warning about installing peer dependencies. I know this is an existing issue with newman but do you know when it is going to be resolved?**

C:\Users>npm install -g newman-reporter-html
npm WARN newman-reporter-html@1.0.2 requires a peer of newman@4 but none is installed. You must install peer dependencies yourself.
+ newman-reporter-html@1.0.2
updated 1 package in 1.33s

**Comment by ssr240** [comment]
I was able to resolve this by updating powershell to latest version. Looks like html reports are not generated with powershell 4.0
