### ISSUE TITLE
add some custom html templates

### ISSUE THREAD

**Issue by hgupta-cs** [postmanlabs/newman-reporter-html#96]
Add some custom templeates  from https://www.npmjs.com/package/newman-reporter-htmlextra

**Comment by DannyDainton** [comment]
Hey @hgupta-cs

As much as those would _probably_ work with this reporter, they have been created with some additional features in mind. 

Parts of the information would be missing from the final output, if you use them with the standard html reporter. 

If you like the templates from that reporter, you _could_ just continue to use that one. It's basically that same anyway 😁
